title: "Vice City Cigars"
tagline: "Your Mobile Tropical Smoking Oasis"
description: "Premium cigars, pipes, hookahs, and mobile event services in Boca Raton. Tropical, laid-back, and expert hospitality."
locale: en_US
# Set your production URL and baseurl for GitHub Pages.
# Example for user/organization site: url: "https://your-username.github.io" and baseurl: ""
# Example for project site:      url: "https://your-username.github.io" and baseurl: "/vcc-website"
url: "https://your-username.github.io"
baseurl: ""
social:
  instagram: "https://instagram.com/vicecitycigars"
  email: "info@vicecitycigars.com"
  phone: "+1-561-555-2121"
theme: null
markdown: kramdown
sass:
  style: compressed
permalink: pretty
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .vscode
  - package.json
  - package-lock.json
plugins: []
collections:
  posts:
    output: true
